us_voices = {
    "Ava (Female)": "en-US-AvaNeural",
    "Andrew (Male)": "en-US-AndrewNeural",
    "Emma (Female)": "en-US-EmmaNeural",
    "Brian (Male)": "en-US-BrianNeural",
    "Jenny (Female)": "en-US-JennyNeural",
    "Guy (Male)": "en-US-GuyNeural",
    "Aria (Female)": "en-US-AriaNeural",
    "Davis (Male)": "en-US-DavisNeural",
    "Jane (Female)": "en-US-JaneNeural",
    "Jason (Male)": "en-US-JasonNeural",
    "Kai (Male)": "en-US-KaiNeural",
    "Luna (Female)": "en-US-LunaNeural",
    "Sara (Female)": "en-US-SaraNeural",
    "Tony (Male)": "en-US-TonyNeural",
    "Nancy (Female)": "en-US-NancyNeural",
    "Andrew Dragon HD (Male)": "en-US-Andrew:DragonHDLatestNeural1",
    "Aria Dragon HD (Female)": "en-US-Aria:DragonHDLatestNeural1",
    "Brian Dragon HD (Male)": "en-US-Brian:DragonHDLatestNeural1",
    "Davis Dragon HD (Male)": "en-US-Davis:DragonHDLatestNeural1",
    "Emma Dragon HD (Female)": "en-US-Emma:DragonHDLatestNeural1",
    "Jenny Dragon HD (Female)": "en-US-Jenny:DragonHDLatestNeural1",
    "Steffan Dragon HD (Male)": "en-US-Steffan:DragonHDLatestNeural1",
}
